source 'https://github.com/CocoaPods/Specs.git'


target 'HYVConfiguratorAFNetworking-Mantle', :exclusive => true do
  pod "HYVConfiguratorAFNetworking-Mantle", :path => "../"

pod 'AFNetworking', '~> 2.5.0'
pod 'Mantle', '~> 1.5.3'

  
end
