source 'https://github.com/CocoaPods/Specs.git'


target 'HYVConfiguratorAFNetworking-Mantle', :exclusive => true do
  pod 'HYVConfiguratorAFNetworking-Mantle', '~> 0.1.1.42'

pod 'AFNetworking', '~> 2.5.0'
pod 'Mantle', '~> 1.5.3'

  
end
